---
- hosts: webservers
  gather_facts: true
  become:  true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install Nginx
      apt: pkg=nginx state=present
      notify:
        - restart nginx
    - name: Enable Nginx during boot
      service: name=nginx state=restarted enabled=true
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted