---
- hosts: webservers
  gather_facts: true
  become:  true
  tasks:
    - name: Install Nginx
      apt: pkg=nginx state=present
      notify:
        - restart nginx
    - name: Enable Nginx during boot
      service: name=nginx state=restarted enabled=true
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted